const MenuItem=[
    {
        id: 1,
        image: "image/menu-item-thumbnail-01.jpg",
        category: "starters",
        title : "GARLIC BREAD",
        price: "$8.5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 2,
        image: "image/menu-item-thumbnail-02.jpg",
        category: "starters",
        title : "MIXED SALAD",
        price: "$25",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 3,
        image: "image/menu-item-thumbnail-03.jpg",
        category: "starters",
        title : "BBQ CHICKEN WINGS",
        price: "$10",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 4,
        image: "image/menu-item-thumbnail-04.jpg",
        category: "main_dish",
        title : "MEAT FEAST PIZZA",
        price: "$5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 5,
        image: "image/menu-item-thumbnail-05.jpg",
        category: "main_dish",
        title : "CHICKEN TIKKA MASALA",
        price: "$15",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 6,
        image: "image/menu-item-thumbnail-06.jpg",
        category: "main_dish",
        title : "SPICY MEATBALLS",
        price: "$6.5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 7,
        image: "image/menu-item-thumbnail-07.jpg",
        category: "deserts",
        title : "CHOCOLATE FUDGECAKED",
        price: "$4.5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 8,
        image: "image/menu-item-thumbnail-08.jpg",
        category: "deserts",
        title : "CHICKEN TIKKA MASALA",
        price: "$9.5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 9,
        image: "image/menu-item-thumbnail-09.jpg",
        category: "deserts",
        title : "CHICKEN TIKKA MASALA",
        price: "$10",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 10,
        image: "image/menu-item-thumbnail-10.jpg",
        category: "drinks",
        title : "MEAT FEAST PIZZA",
        price: "$12.5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 11,
        image: "image/menu-item-thumbnail-09.jpg",
        category: "drinks",
        title : "CHICKEN TIKKA MASALA",
        price: "$9.5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
    {
        id: 12,
        image: "image/menu-item-thumbnail-08.jpg",
        category: "drinks",
        title : "CHICKEN TIKKA MASALA",
        price: "$5.5",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mollis eleifend dapibus.",
    },
]

export default MenuItem;
